version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/jethro_solutions
      - JWT_SECRET=devjwtsecretkey
      - JWT_EXPIRE=30d
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 